defmodule Mix.Tasks.Starter.Run do
  @shortdoc "Runs your project's workflow"

  @moduledoc """
  Finds the workflow generated by `mix starter.new` and runs it, passing all
  flags through.

      mix starter.run
      mix starter.run --oban-pro --gigalixir

  Equivalent to invoking the workflow task directly (e.g. `mix my_app.workflow`).
  """

  use Mix.Task

  @impl Mix.Task
  def run(argv) do
    Mix.Task.run("compile", [])

    case workflow_modules() do
      [module] ->
        Mix.Task.run(Mix.Task.task_name(module), argv)

      [] ->
        Mix.raise("""
        No workflow found in this project.

        Generate one with:

            mix starter.new
        """)

      modules ->
        tasks = Enum.map_join(modules, "\n", &"    mix #{Mix.Task.task_name(&1)}")

        Mix.raise("""
        Multiple workflows found. Run one directly:

        #{tasks}
        """)
    end
  end

  defp workflow_modules do
    app = Mix.Project.config()[:app]

    # get_key only works on loaded applications, and `mix compile` does not
    # reliably load the app (Mix version dependent) — load it explicitly.
    Application.load(app)

    case :application.get_key(app, :modules) do
      {:ok, modules} -> find_workflow_modules(modules)
      _ -> []
    end
  end

  @doc false
  # Public for testing: filters a module list down to workflow task modules.
  def find_workflow_modules(modules) do
    Enum.filter(modules, fn module ->
      String.starts_with?(Atom.to_string(module), "Elixir.Mix.Tasks.") and
        Code.ensure_loaded?(module) and
        function_exported?(module, :__starter_workflow__?, 0)
    end)
  end
end
