defmodule Mix.Tasks.Starter.New do
  @shortdoc "Generates your project's workflow"

  @moduledoc """
  Generates `lib/mix/tasks/<app>.workflow.ex` containing your project's workflow.

  The generated file lists every built-in step in a sensible order, each with
  a one-line description pulled from the step itself. It is data, not
  machinery: delete what you don't want, reorder freely, add your own steps.
  Run it with:

      mix starter.run

  ## Generating from a shared workflow

  Pass `--from` with a workflow module (from a dependency, e.g. your personal
  step pack) to expand *its* steps into the generated file instead of the
  built-in catalog:

      mix starter.new --from StarterJamil.Workflow

  The generated file copies the shared workflow's steps, so the app owns and
  can edit its setup while your pack remains the template.
  """

  use Igniter.Mix.Task

  # The workflow written into new projects: every built-in step, grouped and
  # ordered, with taste-heavy or license-gated steps behind flags. Step
  # descriptions are rendered from each module's @shortdoc at generation
  # time, so the file can never drift from the actual catalog.
  @sections [
    {"Undo phx.new defaults you don't want",
     [
       {:remove, :agents_md},
       {:remove, :daisy_ui},
       {:remove, :live_title_suffix},
       {:remove, :theme_toggle},
       {:remove, :topbar}
     ]},
    {"Generate configuration and code",
     [
       {:gen, :minimal_app_layout},
       {:gen, :minimal_home_page},
       {:gen, :tailwind_formatter},
       {:gen, :gitignore},
       {:gen, :pg_extensions},
       {:gen, :generator_defaults},
       {:gen, :base_schema},
       {:gen, :mix_env_config}
     ]},
    {"Add packages",
     [
       {:add, :bun},
       {:add, :credo},
       {:add, :dotenv_parser},
       {:add, :exsync, if: :exsync},
       {:add, :libcluster},
       {:add, :pgvector},
       {:add, :quokka},
       {:add, :remixicons},
       {:add, :uuidv7},
       {:add, :mix_test_watch, if: :mix_test_watch},
       # No built-in step: these ship their own installers, which run here.
       {:add, :oban},
       {:add, :oban_web},
       {:add, :tidewave},
       # Patches what oban's installer wrote, so it follows it in the list.
       {:add, :oban_pro, if: :oban_pro}
     ]},
    {"Deployment",
     [
       {:gen, :gigalixir, if: :gigalixir},
       {:gen, :gigalixir_libcluster, if: :gigalixir}
     ]},
    {"Tidy mix.exs",
     [
       {:gen, :ecto_force_drop},
       # Last, so it also sorts the deps the steps above added
       {:gen, :sort_deps}
     ]}
  ]

  @impl Igniter.Mix.Task
  def info(_argv, _composing_task) do
    %Igniter.Mix.Task.Info{
      schema: [from: :string],
      example: "mix starter.new --from StarterJamil.Workflow"
    }
  end

  @impl Igniter.Mix.Task
  def igniter(igniter) do
    app_name = Igniter.Project.Application.app_name(igniter)
    app_module = app_name |> to_string() |> Macro.camelize()

    {body, origin} =
      case igniter.args.options[:from] do
        nil -> {sections_block(), nil}
        from -> {from_block(from), from}
      end

    igniter
    |> Igniter.create_new_file(
      "lib/mix/tasks/#{app_name}.workflow.ex",
      workflow_source(app_module, body, origin)
    )
    |> Igniter.add_notice("""
    Your workflow lives at lib/mix/tasks/#{app_name}.workflow.ex — every step is
    documented in place. Edit the list, then run it with:

        mix starter.run

    When it finishes, set up the database and start the server:

        mix ecto.setup && mix phx.server

    Browse individual steps with `mix starter.add --list`,
    `mix starter.remove --list`, and `mix starter.gen --list`.
    """)
  end

  defp workflow_source(app_module, body, origin) do
    origin_note =
      if origin do
        " from `#{origin}` — edits here do not affect the shared workflow"
      else
        ""
      end

    source = """
    # Starter is a dev-only dependency, so this task is only defined when
    # Starter is available. In other environments (test, prod) this file
    # compiles to nothing — do not remove the surrounding `if`.
    if Code.ensure_loaded?(Starter.Workflow) do
      defmodule Mix.Tasks.#{app_module}.Workflow do
        @shortdoc "Runs this project's setup workflow"

        @moduledoc \"\"\"
        This project's setup workflow, generated by `mix starter.new`#{origin_note}.

            mix starter.run
            mix starter.run --oban-pro --gigalixir

        ## How this file works

        Steps run top to bottom. Each is a small Igniter task that patches the
        project, and every change is shown as a diff before it is applied.

          * This file is yours: delete steps you don't want, reorder freely.
          * Steps tagged `if: :flag` only run when you pass the matching
            `--flag`. Tag any step to make it optional — flags are derived
            automatically.
          * `{:add, :name}` gets a package into the app: a built-in step when
            Starter ships one, otherwise the package's own installer. Each run
            prints a plan showing which applied.
          * Compose any Igniter task: `{:task, "some.igniter.task"}`
          * Include a shared workflow: `{:workflow, SomeSharedWorkflow}`
          * Write your own step — any module that `use Igniter.Mix.Task` — and
            list it directly: `#{app_module}.Steps.MyCustomStep`

        Browse built-in steps with `mix starter.add --list`,
        `mix starter.remove --list`, and `mix starter.gen --list`.
        Docs: https://hexdocs.pm/starter
        \"\"\"

        use Starter.Workflow

        @impl Starter.Workflow
        def steps do
          [
    #{body}
          ]
        end
      end
    end
    """

    source
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> Kernel.<>("\n")
  end

  defp sections_block do
    @sections
    |> Enum.map(&render_section/1)
    |> Enum.join(",\n\n")
  end

  defp render_section({title, steps}) do
    body =
      steps
      |> Enum.map(&render_step/1)
      |> Enum.join(",\n")

    "      ## #{title}\n" <> body
  end

  defp from_block(from) do
    module = resolve_workflow!(from)

    module.steps()
    |> Enum.map(&render_step/1)
    |> Enum.join(",\n")
  end

  defp resolve_workflow!(from) do
    module = Module.concat([from])

    if Code.ensure_loaded?(module) and function_exported?(module, :__starter_workflow__?, 0) do
      module
    else
      Mix.raise("""
      #{from} is not a Starter workflow.

      Pass a module that uses Starter.Workflow and is available in this
      project (usually from a dependency), e.g.:

          mix starter.new --from MyTeam.Workflow
      """)
    end
  end

  defp render_step(step) do
    {code, comment} = describe(step)
    "      # #{comment}\n      #{code}"
  end

  defp describe({:add, name}) do
    {"{:add, :#{name}}", add_doc(name)}
  end

  defp describe({:add, name, [if: flag]}) do
    {"{:add, :#{name}, if: :#{flag}}", "#{add_doc(name)} #{flag_note(flag)}"}
  end

  defp describe({kind, name}) when kind in [:remove, :gen] do
    {"{:#{kind}, :#{name}}", shortdoc(kind, name)}
  end

  defp describe({kind, name, [if: flag]}) when kind in [:remove, :gen] do
    {"{:#{kind}, :#{name}, if: :#{flag}}", "#{shortdoc(kind, name)} #{flag_note(flag)}"}
  end

  defp describe({:install, package}) do
    {"{:install, :#{package}}", "Installs #{package} via the package's own igniter installer"}
  end

  defp describe({:install, package, [if: flag]}) do
    {"{:install, :#{package}, if: :#{flag}}",
     "Installs #{package} via the package's own igniter installer #{flag_note(flag)}"}
  end

  defp describe({:queue, task}), do: describe({:queue, task, []})

  defp describe({:queue, task, argv}) do
    {"{:queue, #{inspect(task)}, #{inspect(argv)}}",
     "Queues `mix #{Enum.join([task | argv], " ")}` to run after this run applies"}
  end

  defp describe({:queue, task, argv, [if: flag]}) do
    {"{:queue, #{inspect(task)}, #{inspect(argv)}, if: :#{flag}}",
     "Queues `mix #{Enum.join([task | argv], " ")}` to run after this run applies #{flag_note(flag)}"}
  end

  defp describe({:task, task}), do: describe({:task, task, []})

  defp describe({:task, task, argv}) do
    {"{:task, #{inspect(task)}, #{inspect(argv)}}", "Composes `mix #{task}`"}
  end

  defp describe({:task, task, argv, [if: flag]}) do
    {"{:task, #{inspect(task)}, #{inspect(argv)}, if: :#{flag}}",
     "Composes `mix #{task}` #{flag_note(flag)}"}
  end

  defp describe({:workflow, module}) do
    {"{:workflow, #{inspect(module)}}", "Includes the #{inspect(module)} workflow"}
  end

  defp describe({:workflow, module, [if: flag]}) do
    {"{:workflow, #{inspect(module)}, if: :#{flag}}",
     "Includes the #{inspect(module)} workflow #{flag_note(flag)}"}
  end

  defp describe({module, [if: flag]}) when is_atom(module) do
    {"{#{inspect(module)}, if: :#{flag}}", "#{module_doc(module)} #{flag_note(flag)}"}
  end

  defp describe(module) when is_atom(module) do
    {inspect(module), module_doc(module)}
  end

  defp module_doc(module) do
    if Code.ensure_loaded?(module) do
      Mix.Task.shortdoc(module) || "Custom step"
    else
      "Custom step"
    end
  end

  # `{:add, name}` has no built-in step when the package ships its own
  # installer, which is the normal case rather than an error.
  defp add_doc(name) do
    case Starter.Steps.resolve(:add, name) do
      {:ok, module} -> Mix.Task.shortdoc(module) || to_string(name)
      :error -> "Installs #{name} and runs the package's own igniter installer"
    end
  end

  defp shortdoc(kind, name) do
    case Starter.Steps.resolve(kind, name) do
      {:ok, module} -> Mix.Task.shortdoc(module) || to_string(name)
      :error -> raise "workflow references unknown step: {#{kind}, #{name}}"
    end
  end

  defp flag_note(flag), do: "(only with --#{String.replace(to_string(flag), "_", "-")})"
end
